"""Cliente genérico do Sunday (V1) — só contratos confirmados na Fase 0."""

from classificacao_procons.sunday.client import UNSET, SundayClient
from classificacao_procons.sunday.errors import (
    SundayAuthError,
    SundayConfigError,
    SundayConflictError,
    SundayError,
    SundayForbiddenError,
    SundayHTTPError,
    SundayNotFoundError,
    SundayRelationIntegrityError,
    SundayValidationError,
    SundayVerifyError,
)
from classificacao_procons.sunday.http import SundayConfig
from classificacao_procons.sunday.models import (
    Attachment,
    Board,
    Column,
    Comment,
    Group,
    Item,
    ItemsResult,
    ItemValue,
    StatusOption,
    SundayUser,
    ValuesResult,
    Workspace,
    WorkspaceBoardRef,
    format_target_date,
    normalize_relation_value,
    parse_sunday_date,
)
from classificacao_procons.sunday.tracking import MigrationRecord, MigrationStatus

__all__ = [
    "UNSET",
    "Attachment",
    "Board",
    "Column",
    "Comment",
    "Group",
    "Item",
    "ItemValue",
    "ItemsResult",
    "MigrationRecord",
    "MigrationStatus",
    "StatusOption",
    "SundayAuthError",
    "SundayClient",
    "SundayConfig",
    "SundayConfigError",
    "SundayConflictError",
    "SundayError",
    "SundayForbiddenError",
    "SundayHTTPError",
    "SundayNotFoundError",
    "SundayRelationIntegrityError",
    "SundayUser",
    "SundayValidationError",
    "SundayVerifyError",
    "ValuesResult",
    "Workspace",
    "WorkspaceBoardRef",
    "format_target_date",
    "normalize_relation_value",
    "parse_sunday_date",
]
